### ISSUE TITLE
Cards overlapping

### ISSUE THREAD

**Issue by Saorsa32** [DeusEx01/Cards-View-snippet#2]
I love how this snippet makes my cards look and I like that there are so many options.
When I need to split my screen between obsidian and a web browser, my cards overlap each other. Is there a way for me to prevent this from happening? Also I would love to have a way to set how many cards are in a row. Minimal cards has a way to do this and it resizes the cards to fit the number.

**Comment by Sem1ra1** [comment]
Hi! I appreciate it's useful for you. Could you make a screenshot of  your case(or record gif, video) so I could understand the issue properly? By default it has to prevent such behavior. (Maybe I'm wrong though).
This is how it looks in my case:

![show2](https://github.com/user-attachments/assets/4ad6c82b-5c0f-46c5-a5a1-089dd3501aad)

And about your second question.
There is, unfortunately, no way to do it with current settings. I didn't want to make second Minimal Cards since they already have such interesting behavior 🤷‍♂️
I wanted to make everything fixed. This is a 'philosophy' of the snippet 😊. 
Currently I'm working on creating other thing and don't have time to upgrade the snippet even more. 😌

**Comment by Saorsa32** [comment]
Thank you for getting back to me so soon. I understand what you mean about it having everything fixed. Since I have no understanding of how to make a snippet work, I really appreciate you sharing it with others.

Here is what I am experiencing.
![Screenshot (77)](https://github.com/user-attachments/assets/611cec02-0242-4cdf-b895-2516741ecd81)

**Comment by Saorsa32** [comment]
Thank you for getting back to me so soon. I understand what you mean about it having everything fixed. Since I have no understanding of how to make a snippet work, I really appreciate you sharing it with others. Actually, I just figured it out. I had a different css that was interfering. So now it works great. Thanks!
